config/routes.rb
MyBook::Application.routes.draw do
  resources :posts

  resources :users
  get "/" => "pages#index"
  post "/" => "pages#new_post"
  post "/new_comment" => "pages#new_comment"

end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps

  field :content, type: String
  field :comments, type: Array
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::MultiParameterAttributes

  field :first_name, type: String
  field :last_name, type: String
  field :education, type: String
  field :hobby, type: String
  field :birthday, type: Date
  field :relationship, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery




end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index 
    @user = User.first
    @posts = Post.all.desc(:created_at)
  end

  def new_comment
    post = Post.find_by(id:params[:post])
    if post
      post.comments << params[:content]
      post.save!
    end
    redirect_to '/'
  end

  def new_post
    content = params[:content]
    @post = Post.create(content:content)
    @post.comments = []
    if @post.save!
        respond_to do |format|
          format.html { redirect_to '/' }
          format.js
        end
    else
      render json: {error: "shit"}
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.comments = []

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target="#nav-collapse-01"></button>
            <a href="/" class="brand"><img src="/assets/banner.jpg" width="70px" ></a>
            <div class="nav-collapse collapse" id="nav-collapse-01">
              <ul class="nav">
                <li class="active">
                  <a href= "#{}">Profile</a>
                </li>
                <li>
                  <a href= "#{}">Settings</a>
                </li>
                <ul>
                  <!-- Sub Menu items go here -->
                </ul>
              </li>
            </ul>
          </div>
        </div>

      </div>
    </div>
<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div class="container">
  <!--navbar-->
  <div class="row">
    <div class="span10 offset1" style="position: relative">
      <div class="cover">
        <img class="profilePic" src="/assets/profile.jpg"></img>
      </div>
    </div>
    <div class="span10">
      <p></p>
    </div>
  </div>

  <div class ="row">
    <div class="span3 offset1">
      <div class="popover bottom">
        <div class="arrow"></div>
        <h3 class="popover-title"><%= @user.first_name%> <%= @user.last_name%></h3>

        <div class="popover-content">
          <p>Studied at : <%= @user.education %></p>
          <p>Hobbies : <%= @user.hobby %></p>
          <p>Birthday : <%= @user.birthday.to_s %></p>
          <p>In Relationship with : <%= @user.relationship %></p>
          <%= link_to 'Edit',edit_user_path(@user), class:"btn btn-info btn-mini" %>
          <p></p>
        </div>
      </div>
    </div>

    <div class="span6">
     <div style="background-color: #E2E2E2; padding: 15px 15px 2px 15px; border-radius: 20px">     
      <%= form_tag("/", method: "post", class:"new_post") do %>
      <%= text_area_tag :content,nil, class:"span12 content", placeholder:"What's on your mind", row:"3" %>
      <%= submit_tag("Post", class:"btn") %>
      <% end %>

    </div>
    <br>
    <div style="background-color: #E2E2E2; padding: 15px 15px 2px 1px; border-radius: 20px">
      <ul class="posts_list" >
        <% for post in @posts %>
        <li class="post">
          <div class= "postHeader" >
            <div class="span1 crop">
              <img class= "span1 commentImage" src="/assets/profile.jpg" >
            </div>
            <p class= "postName"><%= @user.first_name%> <%= @user.last_name%></p>
          </div> 
          <div class="postContent">

            <%= post.content %>

          </div>

          <div class="separator"></div>

          <div class="commentSection">

            <ul class="comment">
              <% for comment in post.comments %>
                <li><%= comment %></li>
              <% end %>
            </ul>

          </div>


          <div class="row" style="background-color: #E2E2E2">
            <div class="span3" style="background-color: #E2E2E2; padding-left:4px">
              <div style="background-color: #E2E2E2; padding: 15px 15px 2px 15px; border-radius: 20px">     
                <%= form_tag("/new_comment", method: "post", class:"row") do %>
                <%= hidden_field_tag :post, post.id %>

                <%= text_area_tag :content,nil, class:"offset commentField", placeholder:"Write a comment...", row:"1" %>
                <%= submit_tag("Comment", class:"btn btn-small btn-primary commentButton") %>

                <% end %>

              </div>
            </div>
          </div>
        </li>
        <br>
        <% end %>


      </ul>
    </div>
  </div>

</div>  
</div>
</div>

app/views/pages/new_post.js.erb
$("textarea.content").val("");

var head =  "<div class='postHeader'>" +
            "<img src='/assets/profile.jpg' class='span1 commentImage'>"+
            "<p>Sivabudh Umpudh</p>"+
          "</div>";

var status = "<li class='post'>" + head +
          "<div class='postContent'>" +
          "<p><%= @post.content %></p>" +
          "</div>"+
          "</li>";

$("ul.posts_list").prepend(status);

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :education %><br />
    <%= f.text_field :education %>
  </div>
  <div class="field">
    <%= f.label :hobby %><br />
    <%= f.text_field :hobby %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :relationship %><br />
    <%= f.text_field :relationship %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', '/' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>

    <th>Education</th>
    <th>Hobby</th>
    <th>Birthday</th>
    <th>Relationship</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>

    <td><%= user.education %></td>
    <td><%= user.hobby %></td>
    <td><%= user.birthday %></td>
    <td><%= user.relationship %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>First Name:</b>
  <%= @user.first_name %>
</p>
<p>
  <b>Last Name:</b>
  <%= @user.last_name %>
</p>
<p>
  <b>Education:</b>
  <%= @user.education %>
</p>

<p>
  <b>Hobby:</b>
  <%= @user.hobby %>
</p>

<p>
  <b>Birthday:</b>
  <%= @user.birthday %>
</p>

<p>
  <b>Relationship:</b>
  <%= @user.relationship %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', '/' %>